In [1]:
import numpy as np

# np.full()

In [2]:
# 하나의 특정 값으로 배열의 값을 채우고 싶을 때는
# np.full() 메서드를 활용하면 좋다.

# numpy.full(shape, fill_value, dtype = None, 
#            order = 'C', *, like = None)

# 첫 번째 인자에는 shape을, 두 번째 인자에는 요소로 채울 값 전달
# 타입 명기를 원하면 dtype 키워드 인수 작성

np.full((3, 3, 3), '', dtype = "U10")

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

# 단위 행렬 만들기

In [3]:
# 크기가 n인 단위 행렬은 numpy에서 np.eye(n)메서드로 생성
# 기본 타입은 float이며, dtype 키워드 인수로 데이터 타입 지정 가능

np.eye(4, dtype = 'i')


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

# 넘파이 배열 데이터 타입 변경하기

In [4]:
# 넘파이 배열 데이터 타입 변경하기

# ndarray 타입을 변경하기 위해서 astype()메서드 사용

# ndarray.astype(dtype, order = 'K', castings = 'unsafe',
#                subok = True, copy = True)

# 첫번째 위치 키워드 인수인 dtype은 값을 필수로 입력해줘야 한다.

In [5]:
a = np.ones((2, 3, 4))
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [6]:
a.astype("i")

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

# Boolean indexing

In [7]:
# 같은 shape과 len의 boolean type의 값을 갖는 ndarray로 인덱싱 가능
# 해당 위치에 대해 True면 값을 취하고 False면 가져오지 않는다.

In [8]:
a = np.arange(1, 5)
print(a)

[1 2 3 4]


In [9]:
even = np.array([True if i%2 == 0 else False for i in range(1, 5)])
print(even)

[False  True False  True]


In [10]:
a[even] # 짝수인 것만 반환한다.

array([2, 4])