In [1]:
import numpy as np

In [2]:
# 복습
np.random.seed(0)
trial = np.random.randint(1, 7, 100)
np.mean(trial)

3.42

In [3]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[7, 8, 9], [10, 11, 12]])

a1 + a2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [4]:
a3 = np.arange(1, 10)
a3 * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
a4 = np.zeros(10)
a4[4] = 1
a4

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
a5 = np.arange(50)
np.sort(a5)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [7]:
a5[np.argsort(-a5)]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [8]:
a6 = np.zeros((3, 3, 3), dtype = 'U10')
a6

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [9]:
a7 = np.full((3, 3, 3), 'playdata')
a7

array([[['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']]], dtype='<U8')

In [10]:
a8 = np.arange(2, 41, 2).reshape(2, 2, 5)
a8

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])