In [1]:
import numpy as np

In [2]:
# 복습
np.random.seed(0)
trial = np.random.randint(1, 7, 100)
np.mean(trial)

3.42

In [3]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[7, 8, 9], [10, 11, 12]])

a1 + a2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [4]:
a3 = (np.arange(1, 10))*3
a3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
a4 = np.zeros(10)
a4[4] = 1
a4

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
a5 = np.arange(50)
np.sort(a5)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [7]:
a5[np.argsort(-a5)]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [8]:
a5[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [9]:
a6 = np.zeros((3, 3, 3), dtype = 'U10')
a6

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [10]:
a7 = np.full((3, 3, 3), 'playdata')
a7

array([[['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']]], dtype='<U8')

In [11]:
a8 = np.arange(2, 41, 2).reshape(2, 2, 5)
a8

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

In [12]:
np.eye(4, dtype = 'i')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [13]:
np.random.seed(0)
a9 = np.random.randint(0, 2, 9).astype('?').reshape(3, 3)
a9

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [14]:
np.random.seed(0)
a10 = (np.random.rand(10)*10).astype('i')
a10

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3], dtype=int32)

In [15]:
a11 = np.ones((10, 10))
a11[1:-1, 1:-1] = 0
a11

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
a12 = np.ones((10, 10))
for i in range(10):
    if i == 0:
        a12[i] = 0
        a12[:,i] = 0
    elif i == 9:
        a12[i] = 0
        a12[:,i] = 0
a12

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
a12 = np.ones((10, 10))
a12[0] = 0
a12[:,0] = 0
a12[-1] = 0
a12[:,-1] = 0
a12

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
a12 = np.ones((10, 10))
a12[::9, :] = 0
a12[:, ::9] = 0
a12

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
a12 = np.ones((10, 10))
a12[:, [0, -1]] = 0 # 모든 행에 대하여 0번 열과 -1번 열을 0으로 만든다.
a12[[0, -1], :] = 0 # 모든 열에 대하여 0번 행과 -1번 행을 0으로 만든다.
a12

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
a13 = np.ones((8,8)).astype('i')
for i in range(8):
    if i % 2 == 0:
        a13[i, 1::2] = 0
    else:
        a13[i, ::2] = 0
a13

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int32)

In [21]:
a13 = np.ones((8,8)).astype('i')
a13[::2, 1::2] = 0
a13[1::2, ::2] = 0
a13

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int32)

In [22]:
a14 = np.tile(np.eye(2), (4,4))
a14

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [23]:
a15 = np.arange(11)
minus = np.array([-1*True if 3 < i < 7 else True for i in range(11)])
a15_minus = a15*minus
a15_minus

array([ 0,  1,  2,  3, -4, -5, -6,  7,  8,  9, 10])

In [24]:
a15 = np.array([-i if 3 < i < 7 else i for i in range(11)])
a15

array([ 0,  1,  2,  3, -4, -5, -6,  7,  8,  9, 10])

In [25]:
a15 = np.arange(11)
a15[(3 < a15)  & (7 > a15)] *= -1
print(a15)

[ 0  1  2  3 -4 -5 -6  7  8  9 10]


In [26]:
a16 = np.arange(1,101)
div3 = np.array([True if i%3 == 0 else False for i in range(1, 101)])
arr = a16[div3]
np.sum(arr)

1683

In [27]:
a16 = np.arange(3, 101, 3)
np.sum(a16)

1683

In [28]:
a17 = np.linspace(0.1, 0.9, 9)
a17

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [29]:
while True:    
    try:
        n1 = int(input())
        if n1 <= 0:
            print("자연수만 입력해주세요.")
            continue
        else:
            for i in range(n1):
                lis = []
                a18= np.random.choice(range(1, 46), 6, replace = False)
                lis.extend(a18)
                lis.sort()
                display(lis)
        break
    except ValueError:
        print("자연수만 입력해주세요.")
        continue

 3


[7, 33, 35, 37, 44, 45]

[3, 14, 17, 23, 25, 34]

[6, 8, 13, 17, 23, 38]

In [30]:
# while True:
#     try:
#         number = int(input())
#         if number>0:
#             for _ in range(number):
#                 result = np.random.choice(range(1, 46), size=6, replace=False)
#                 result.sort()
#                 print(result)
#             break
#         else:
#             print("자연수만 입력해주세요.")
#     except ValueError:
#         print("자연수만 입력해주세요.")
#         continue

In [31]:
# while True:
#     try:
#         n = input("자연수를 입력해주세요.")
#         if n <= 0:
#             raise Error
#         numbers = np.arange(1, 46)
#         lottos = [np.sort(np.random.choice(numbers, 6, replace = False)) for _ in range(n)]
#         display(lottos)
#         break
#     except:
#         print("자연수를 입력해주세요.")

In [32]:
while True:
    n = int(input("자연수만 입력해주세요."))
    try:
        if n<=0:
            continue;
        k = [np.random.choice(range(1, 46), size=6, replace=False) for _ in range(n)]
        display(np.sort(k))
        break;
    except ValueError:
        continue;

자연수만 입력해주세요. 3


array([[ 2,  8, 11, 18, 24, 39],
       [10, 15, 18, 33, 34, 42],
       [ 7, 17, 20, 29, 31, 34]])

In [33]:
resp_time = np.array([158, 85, 205, 24, 42, 175, 188, 149, 153, 171, 137, 55, 108,
                    199, 177, 209, 218, 76, 103, 189, 110, 192, 136, 119, 4, 102,
                    177, 212, 110, 37, 163, 32, 77, 22, 125, 184, 46, 139, 72,
                    168, 133, 209, 148, 47, 102, 65, 160, 56, 11, 96, 169, 118,
                    55, 135, 217, 49, 100, 85, 179, 15, 139, 199, 124, 142, 15,
                    49, 168, 171, 168, 177, 147, 23, 199, 26, 51, 42, 90, 128,
                    186, 169, 129, 70, 198, 111, 81, 150, 17, 177, 201, 10, 75,
                    199, 55, 151, 183, 152, 119, 193, 110, 204])

In [34]:
a19 = resp_time[np.where(resp_time>200)] # np.where(resp_time>200은
                                         # resp_time 안에서 200을 넘는 값의 인덱스를 반환
                                         # resp_time[np...]은 그 값을 저장
len(a19)

8

In [35]:
a19 = np.array([resp_time>200])
np.sum(a19)

8

In [36]:
(resp_time > 200).sum()

8

In [37]:
a19 = np.array([True if i > 200
                else False
               for i in resp_time])
len(resp_time[a19])

8

In [38]:
a20 = np.percentile(resp_time, 0)
a21 = np.percentile(resp_time, 25)
a22 = np.percentile(resp_time, 50)
a23 = np.percentile(resp_time, 75)
a24 = np.percentile(resp_time, 100)
display(a20, a21, a22, a23, a24)

4.0

71.5

131.0

175.5

218.0

In [39]:
for i, v in enumerate(range(25, 76, 25)):
    print(f"{i + 1}분위({v}값%) 값: {np.percentile(resp_time, v)}ms")

1분위(25값%) 값: 71.5ms
2분위(50값%) 값: 131.0ms
3분위(75값%) 값: 175.5ms


In [40]:
np.quantile(resp_time, 0.75) # 4분위수 계산

175.5

In [41]:
p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
                1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
                1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
                2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
                2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
                2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
                1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
                2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
                0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
                0, 1])

In [42]:
# a25 = result[np.where(result == 0)] # result에서 0이 되는 값 추출
# a25_len = len(a25) # 정수로 길이 저장
# a26 = result[np.where(result == 1)]
# a26_len = len(a26)
# a27 = result[np.where(result == 2)]
# a27_len = len(a27)

# a28 = np.array([a25_len, a26_len, a27_len])
# a29 = np.max(a28) # 최대값 찾기
# a30 = np.argmax(a28) # 최대값 인덱스 찾기

# print(f"{p[a30]}가 {a29}표로 반장으로 선출되었습니다.")

In [43]:
a25 = len(result[np.where(result == 0)])
a26 = len(result[np.where(result == 1)])
a27 = len(result[np.where(result == 2)])

a28 = np.array([a25, a26, a27])

print(f"{p[np.argmax(a28)]}가 {np.max(a28)}표로 반장으로 선출되었습니다.")

뽀로로가 81표로 반장으로 선출되었습니다.


In [44]:
import collections
p=["뽀로로","루피","크롱"]
x=np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
                   1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
                   1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
                   2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
                   2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
                   2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
                   1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
                   2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
                   0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
                   0, 1])
dic = dict(collections.Counter(x))
print(f'{p[max(dic,key=dic.get)]}가(이) {max(dic.values())}표로 반장으로 선출되었습니다.')

뽀로로가(이) 81표로 반장으로 선출되었습니다.


In [45]:
a31 = np.bincount(result, minlength = 3)
print(f"{p[a31.argmax()]}가 {a31.max()}표로 반장으로 선출되었습니다.")

뽀로로가 81표로 반장으로 선출되었습니다.


In [46]:
m, n = np.unique(result, return_counts=True)
print(f"{p[np.argmax(n)]}가 {np.max(n)}표로 반장으로 선출되었습니다.")

뽀로로가 81표로 반장으로 선출되었습니다.


In [47]:
a32 = np.bincount(result, minlength = 3)
print(f"{p[a32.argmin()]}가 {a32.min()}표로 낙선하였습니다.")

루피가 53표로 낙선하였습니다.


In [48]:
counts = [0, 0, 0]
for i in result:
    counts[i] += 1

print(counts)
print(f"{p[counts.index(max(counts))]}가 {max(counts)}표로 반장으로 선출되었습니다.")

[81, 53, 66]
뽀로로가 81표로 반장으로 선출되었습니다.
