In [1]:
# python 리스트는 length, items으로 구성되어 있다.
# length는 시퀀스 길이, items는 요소(주소)이다.
# 다양한 자료형을 섞어서 가질 수 있다.
# 리스트 요소가 shallow copy, deepcopy로 자유롭게 복사 가능
# 메모리 상에 주소가 연속적인 값을 지님

# 반면에 numpy는 data, dimensions, strides로 구성되어 있다.
# data는 이진 데이터, dimensions는 배열 구조(차원), 
# strides는 증감 크기(type 크기)이다.
# 단일 자료형만 가질 수 있다.
# 메모리 상에 연속적인 값을 가짐

In [2]:
import numpy as np

In [3]:
# 1차원 배열 만들기
ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
ar.shape # 1차원의 10칸을 갖는 ndarray

(10,)

In [5]:
type(ar)

numpy.ndarray

In [6]:
ar2 = np.array([0.1, 5, 4, 12, 0.5]) # 하나의 자료형으로 통일
ar2 # 5, 4 ,12가 실수로 통일됨

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [7]:
# 넘파이의 자료형
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [8]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [9]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [10]:
# dtype접두사    type             example 
# '?' :        Boolean          ?(True, False)
# 'i' :          int            i8(64bit)
# 'u' :      unsigned int       u8(64bit)
# 'f' :         float           f8(64bit)
# 'c' :        complex          c16(128bit)
# 'O' :         Object          0(객체에 대한 포인터)
# 'U' :     Unicode string      U24(24 유니코드 글자)

In [11]:
x = np.array([1, 2, 3], dtype = 'f')
x.dtype

dtype('float32')

In [12]:
x[0] + x[1]

3.0

In [13]:
x = np.array([1, 2, 3], dtype = 'U')
x.dtype # 1칸 짜리 공간 생성(1차원)
# 최대한 메모리를 적게 사용하려고 함

dtype('<U1')

In [14]:
x[0] + x[1]

'12'

In [15]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
# 무한대가 값이면 np.inf가 나온다
# 0을 0으로 나눌 경우 np.nan이 나온다.

C:\Users\user\AppData\Local\Temp\ipykernel_11036\169884558.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\user\AppData\Local\Temp\ipykernel_11036\169884558.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [16]:
np.log(0) # 무한대

C:\Users\user\AppData\Local\Temp\ipykernel_11036\1995227575.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0) # 무한대


-inf

In [17]:
np.exp(-np.inf)

0.0

In [18]:
# 벡터화 연산
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] # python list
answer = [2 * d for d in data]
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [19]:
x = np.array(data) # ndarray로 전환
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
2 * x # 1bit를 왼쪽으로 밀어내면 X2, 오른쪽으로 밀면 /2다.
# 따라서 벡터 연산을 하는 numpy가 리스트보다 더 빠른 연산이 가능하다.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
list_samp = [_ for _ in range(3)]
print(list_samp * 5) # 리스트에 곱 연산을 하면 리스트 길이가 연산이 된다.
# 이 예제에서는 list_samp가 5번 곱해짐

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]


In [22]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [23]:
2 * a + b # ndarray는 각 요소에 대하여 연산이 이루어지는 것을 확인 가능
# 만일 ndarray랑 리스트가 연산되면 ndarray를 기준으로 계산된다.

array([12, 24, 36])

In [24]:
a == 2 # 해당 요소가 있는 자리가 True 반환

array([False,  True, False])

In [25]:
a == np.array([2, 2, 2]) # a==2의 구조
# 이를 broadcasting이라고 함

array([False,  True, False])

In [26]:
b > 10

array([False,  True,  True])

In [27]:
(a == 2) & (b > 10) # a 와 b에 and 조건으로 참인 것만 반환
# 이 예제에서는 2번째 요소(1번 인덱스)만 참이다
# & 동작은 비교대상의 비트를 비교한다.
# and과 다름

array([False,  True, False])

In [28]:
(a == 2) and (b > 10) # numpy에서는 and를 쓰면 에러 발생
# &를 통해 비트 연산을 하여 and과 동일한 결과 생성

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [29]:
a == 2 & b > 10 # &가 우선순위가 밀려서 연산이 안 됨

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [30]:
# 2차원 배열 만들기
# axis는 0이 행, 1이 열이다.
# 행 X 열

c = np.array([[0, 1, 2], [3, 4, 5]]) # 2 X 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
# 행의 개수
len(c)

2

In [32]:
# 열의 개수
len(c[0])

3

In [33]:
c.shape

(2, 3)

In [34]:
# 3차원 배열 만들기
# axis는 0이 깊이, 1이 행, 2가 열이다.
# 깊이 X 행 X 열

In [35]:
d = np.array([[[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]],
             [[11, 12, 13, 14], 
              [15, 16, 17, 18],
              [19, 20, 21, 22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [36]:
len(d), len(d[0]), len(d[0][0]) # 한줄에 쓰면 tuple로 인식됨

(2, 3, 4)

In [37]:
d.shape

(2, 3, 4)

In [38]:
# 배열의 차원과 크기 알아내기
# a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)

1
(3,)


In [39]:
# c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [40]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


In [41]:
# 배열의 인덱싱
a = np.array([0, 1, 2, 3, 4])

In [42]:
a[2]

2

In [43]:
a[-1]

4

In [44]:
# 다차원 배열의 인덱싱
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
a[0, 0] # 첫번째 행의 첫번째 열

0

In [46]:
a[0, 1] # 첫번째 행의 두번째 열

1

In [47]:
a[-1, -1] # 마지막 행의 마지막 열

5

In [48]:
#배열의 슬라이싱
a = np.array([[0, 1, 2, 3], [4, 5, 6 ,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [49]:
a[0, :] # 첫번째 행 전체

array([0, 1, 2, 3])

In [50]:
a[:, 1] # 두번째 열 전체

array([1, 5])

In [51]:
a[1, 1:] # 두번째 행의 두번째 열부터 마지막 열까지

array([5, 6, 7])

In [52]:
a[:2, :2] # 두번째 행과 2번째 열까지

array([[0, 1],
       [4, 5]])