In [1]:
import numpy as np

In [2]:
# 배열 생성 명령어

# zeros, ones 크기가 정해져 있고 값이 0이면 zeros, 1이면 ones
# zeros_like, ones_like
# empty
# arange
# linspace, logspace

In [3]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [4]:
a.dtype

dtype('float64')

In [5]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
b.dtype

dtype('float64')

In [7]:
c = np.zeros((5, 2), dtype = 'i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [8]:
c.dtype

dtype('int32')

In [9]:
# zeros 메서드로 생성된 문자열 배열도 생성 가능하다.
# 주의할 점은 모든 요소의 문자열 크기가 같아야 한다.
# 만약 더 큰 크기의 문자열을 할당하면 잘린다.

In [10]:
d = np.zeros(5, dtype = 'U4')
d # dtype 유니코드 스트링을 사용하면 공백으로 구성된 배열 생성 가능

array(['', '', '', '', ''], dtype='<U4')

In [11]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE" # 공간이 4칸이 할당되었으므로 E가 잘린다
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [12]:
e = np.ones((2,3,4), dtype= 'i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [13]:
e.dtype

dtype('int64')

In [14]:
f = np.ones_like(b, dtype = 'f') 
f # ones_like 혹은 zeros_like을 쓰면
# 같은 shape의 배열을 생성하고 값을 ones_like는 1,
# zeros_like는 0으로 값이 채워진다.

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [15]:
# empty를 사용하면 배열을 생성만 하고, 특정한 값으로 초기화를 하지 않는다.
# empty 명령으로 생성된 배열에는 기존에 메모리에 저장되어 있던 값이
# 있으므로 배열의 요소의 값을 미리 알 수 없다.

g = np.empty((4, 3))
g

array([[1.10665574e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 2.33858438e-052],
       [1.91933995e-052, 1.00127652e+165, 8.92801991e+165],
       [5.74096444e+174, 1.34028148e-075, 2.21636479e+160]])

In [16]:
# arange는 Numpy 버전의 range와 같다.
# 특정한 규칙에 따라 증가하는 수열

np.arange(10) # 0 ... n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(3, 21, 2) # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
# linspace나 logspace는 선형 구간 혹은 로그 구간을
# 지정한 구간의 수만큼 분할

ex = np.linspace(0, 100, 5) # 끝 범위가 포함됨
ex

array([  0.,  25.,  50.,  75., 100.])

In [19]:
ex2 = np.logspace(0, 100, 5) # 끝 범위가 포함됨
ex2

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

In [20]:
# 전치 연산(transpose)
# transpose는 행과 열 전환

A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
# 배열의 크기 변형
# 일단 만들어진 배열의 내부 데이터는 보존한 채로 형태만 바꾸려면
# reshape 명령이나 메서드 사용

a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
a.shape

(12,)

In [24]:
a.ndim

1

In [25]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
b.shape

(3, 4)

In [27]:
b.ndim

2

In [28]:
# 사용하는 원소의 개수가 정해져 있기 때문에 reshape 명령의 형태
# 튜플의 원소 중 하나는 -1이라는 숫자로 대체가 가능하다.
# -1을 넣으면 해당 숫자는 다른 값에서 계산되어 사용된다.

a.reshape(3, -1) # 행 3개를 만들고 열은 알아서 구분

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
a.reshape(3, -1).shape

(3, 4)

In [30]:
a.reshape(2, 2, -1) # 깊이와 행을 2개로 만들고 열은 알아서 구분

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [31]:
a.reshape(2, 2, -1).shape

(2, 2, 3)

In [32]:
a.reshape(2, -1, 2) # 깊이와 열을 2개로 만들고 행은 알아서 구분

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [33]:
a.reshape(2, -1, 2).shape

(2, 3, 2)

In [34]:
a.reshape(7,-1).shape # 구분할 숫자가 배열의 요소 숫자로 나누어
# 떨어지지 않을 경우 오류 발생

ValueError: cannot reshape array of size 12 into shape (7,newaxis)

In [35]:
# 다차원 배열을 1차원으로 만들 때는 flatten 혹은 ravel 메서드를 사용한다.
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
a.flatten().shape

(12,)

In [37]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
a.ravel().shape

(12,)

In [39]:
# 형태가 같아 보여도 1차원 배열, 2차원 배열은 엄연히 다르다.

# 아래 예제는 길이가 5인 1차원 배열, 행과 열이 5, 1인 2차원 배열
# 혹은 행과 열이 1, 5인 2차원 배열이 다 다름을 보여준다.

x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [40]:
id(x)

2239933057040

In [41]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [42]:
x.reshape(1, 5)
id(x)

2239933057040

In [43]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [44]:
x.reshape(5,1)
id(x)

2239933057040

In [45]:
# 차원 증가
# 배열에 대하여 1차원 증가시키는 경우에는 nexaxis 명령어 사용

x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [46]:
# 배열 연결 명령어
# 행의 수나 열의 수가 같은 두 개 이상의 배열을 연결(concatenate)하여
# 더 큰 배열을 만들 때 사용

# hstack
# vstack
# dstack
# stack
# r_
# c_
# tile

In [47]:
# hstack 명령은 행의 수가 같은 두 개 이상의 배열을
# 옆으로 연결하여 열의 수가 더 많은 배열을 생성
# 연결할 배열은 하나의 리스트에 담아야 한다.

a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [48]:
a2 = np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [49]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [50]:
# vstack명령은 열의 수가 같은 두 개 이상의 배열을
# 옆으로 연결하여 행의 수가 더 많은 배열을 생성
# 연결할 배열은 하나의 리스트에 담아야 한다.

b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
# dstack명령은 제3의 축 즉, 행이나 열이 아닌 깊이(depth)
# 방향으로 배열을 합친다.
# 가장 안쪽의 원소의 차원이 증가한다.
# 즉 가장 내부의 숫자 원소가 배열이 된다.
# shape 정보로 보면 가장 끝에 값이 2인 차원이 추가되는 것
# 아래 예제의 경우 shape 변화가
# 2개의 (3 X 4) → 1개의 (3 X 4 X 2)가 된다.

c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
np.dstack([c1, c2]) # 두개의 배열이 결합되면서 1개로 통합하는 과정에서
# 열이 하나 늘어나서 마지막 자리가 1이 증가한다.

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [56]:
(np.dstack([c1, c2])).shape

(3, 4, 2)

In [57]:
# stack 명령은 dstack의 기능을 확장한 것으로 dstack처럼
# 마지막 차원으로 연결하는 것이 아니라 사용자가 지정한
# 차원(축으로) 배열을 연결한다.
# axis 인수(default = 0)를 사용하여 연결후의 회전 방향을 정한다.
# 가장 앞쪽 차원에 생성되고, 배열 두개가 겹치게 되므로 연결하고자
# 하는 배열들의 크기가 모두 같아야 한다.

In [58]:
# 아래 예제는 axis = 0이므로 가장 바깥에 값이 2인 차원이 추가
# shape 변화는 2개의 (3 X 4) → 1개의 (2 X 3 X 4)
c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [59]:
c.shape # 어느 축을 합치느냐에 따라 결합한 개수가 보인다.
# axis = 0이면 1번째 자리
# axis = 1이면 2번째 자리
# axis = 2이면 3번째 자리

# 지금은 2개의 배열을 결합했으므로 2가 되고,
# 3개의 배열을 합치면 (3, ?, ?), (?, 3, ?), (?, ?, 3)이 된다.
# 4개의 배열을 합치면 (4, ?, ?), (?, 4, ?), (?, ?, 4)이 된다.

(2, 3, 4)

In [60]:
c = np.stack([c1, c2], axis = 1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [61]:
c.shape

(3, 2, 4)

In [62]:
c = np.stack([c1, c2], axis = 2) # dstack과 동일
c

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [63]:
c.shape

(3, 4, 2)

In [64]:
# r_method
# r_method는 hstack과 비슷하게 배열을 좌우로 연결
# method임에도 불구하고 소괄호(parenthesis,())를 사용하지 않고
# 인덱싱과 같이 대괄호(bracket, [])를 사용한다.
# 이런 특수 메서드를 인덱서(indexer)라고 한다.

# 아래 예제를 보면 row 단위로 결합함

np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [65]:
np.r_[np.array([[1, 2, 3],[4, 5, 6]]), 
      np.array([[7, 8, 9],[10, 11, 12]])]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [66]:
# c_method
# c_method는 배열의 차원을 증가시킨 후 좌우로 연결
# 만약 1차원 베열을 연결하면 2차원 배열이 됨

# 아래 예제를 보면 차원을 1개 올리고, 
# (1,4), (2, 5)와 같이 column 단위로 결합

np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
np.c_[np.array([[1, 2, 3],[4, 5, 6]]), 
      np.array([[7, 8, 9],[10, 11, 12]])]

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [68]:
np.c_[np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]), 
      np.array([[10, 11, 12],[13, 14, 15], [16, 17, 18]])]

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [69]:
# tile
# tile은 배열을 반복하여 연결

a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2) # 가로로 배열 반복

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [70]:
np.tile(a, (3, 2)) # 가로로 2번 반복한 후에 세로로 3번 반복

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])