In [1]:
import numpy as np

In [2]:
# 기술 통계
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2,
             15, 8, 2, 5, 4, 15, -1, 4, -7, -24, 7,
             9, -6, 23, -13])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [3]:
len(x) #  개수

26

In [4]:
np.mean(x) # 표본 평균

4.8076923076923075

In [5]:
np.var(x) # 표본 분산

115.23224852071006

In [6]:
np.var(x, ddof=1) # 비편향 분산

119.84153846153846

In [7]:
np.std(x) # 표준 편차

10.734628476137871

In [8]:
np.max(x) # 최대값

23

In [9]:
np.min(x) # 최소값

-24

In [10]:
np.median(x) # 중앙값
# 개수가 짝수라면 가운데값 2개의 평균을 산출

5.0

In [11]:
# 사분위수
np.min(x) # 최소값

-24

In [12]:
np.median(x) # 중앙값

5.0

In [13]:
np.percentile(x, 0) # 최소값

-24.0

In [14]:
np.percentile(x, 25) # 1사분위 수

0.0

In [15]:
np.percentile(x, 50) # 2사분위 수

5.0

In [16]:
np.percentile(x, 75) # 3사분위 수

10.0

In [17]:
np.percentile(x, 100) # 최대값

23.0

In [18]:
# 난수 발생과 카운팅

# 컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 의미의 무작위 수가 아니다.
# 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열 생성

# 이런 기준이 되는 시작 숫자를 시드(seed)라고 한다.
# 일단 생성된 난수는 다음 번 난수 생성을 위한 시드값이 된다.

# 특정 시드값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측 가능하다.

In [19]:
np.random.seed(0)

In [20]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [21]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [22]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [23]:
# 시드값 초기화
np.random.seed(0)

In [24]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [25]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [26]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [27]:
# 위와 같이 시드 값이 정해지면 동일한 결과가 나오는 것 확인 가능

In [28]:
# 데이터의 순서 바꾸기

# 데이터의 순서를 바꾸려면 shuffle 함수를 사용
# shuffle 함수도 자체 반환(in-place) 함수로 한 번 사용하면 
# 변수의 값이 바뀐다.

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.random.shuffle(x)
x # in-place를 통해 x를 다시 변수로 지정 안 해도 결과가 반영됨
# 주의 필요!!

array([3, 6, 4, 5, 2, 9, 7, 8, 1, 0])

In [30]:
# 데이터 샘플링

# 이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것을
# 표본선택 혹은 샘플링(sampling)이라고 한다.
# 샘플링에는 choice 함수를 사용

# choice 함수는 다음과 같은 인수를 가진다.
# numpy.random.choice(a, size = None, replace = True, p = None)

# a : 배열이면 원래 데이터, 정수이면 arange(a)명령으로 데이터 생성
# size : 정수, 샘플 숫자
# replace : 불리언, True이면 한번 선택한 데이터를 다시 선택 가능
# p : 배열. 각 데이터가 선택될 수 있는 확률

In [31]:
np.random.choice(5, 5, replace = False) # shuffle 명령과 같다.

array([1, 4, 0, 3, 2])

In [32]:
np.random.choice(5, 3, replace = False) # 3개만 선택

array([2, 1, 3])

In [33]:
np.random.choice(5, 10) # 반복해서 10개 선택

array([0, 4, 1, 4, 1, 2, 2, 0, 1, 1])

In [34]:
np.random.choice(5, 10, p =  [0.1, 0, 0.3, 0.6, 0])
# 선택 확률을 다르게 해서 10개 선택

array([0, 3, 3, 2, 2, 3, 3, 2, 0, 3])

In [35]:
# rand 함수는 0부터 1사이에서 균일한 확률 분포로 실수 난수 생성
np.random.rand(10) # 실수를 소수점 아래 8자리까지 생성

array([0.95894927, 0.65279032, 0.63505887, 0.99529957, 0.58185033,
       0.41436859, 0.4746975 , 0.6235101 , 0.33800761, 0.67475232])

In [36]:
np.random.rand(3, 5)

array([[0.31720174, 0.77834548, 0.94957105, 0.66252687, 0.01357164],
       [0.6228461 , 0.67365963, 0.971945  , 0.87819347, 0.50962438],
       [0.05571469, 0.45115921, 0.01998767, 0.44171092, 0.97958673]])

In [37]:
# randn 함수는 기댓값(mean)이 0이고 표준편차가 1인
# 표준 정규분포(standard normal distribution)를 따르는 난수 생성
np.random.randn(10)

array([-0.30237513, -2.2244036 ,  0.72400636,  0.35900276,  1.07612104,
        0.19214083,  0.85292596,  0.01835718,  0.42830357,  0.99627783])

In [38]:
np.random.randn(3, 5)

array([[-0.49114966,  0.71267817,  1.11334035, -2.15367459, -0.41611148],
       [-1.07089699,  0.22113881, -1.12305712, -1.05075796,  1.01207905],
       [ 1.54371643, -0.40211489,  0.8647491 , -0.22686923,  0.81116027]])

In [39]:
# randint
# randint 함수의 인수
# numpy.random.randint(low, high = None, size = None)

# 만약 high를 입력하지 않으면 0과 low 사이의 숫자를, 
# high를 입력하면 low와 high 사이의 숫자를 출력한다.

# size는 난수의 개수

# high의 범위는 포함하지 않는다.

np.random.randint(10, size = 10)

array([0, 4, 3, 6, 9, 8, 0, 8, 5, 9])

In [40]:
np.random.randint(10, 20, size = 10)

array([10, 19, 16, 15, 13, 11, 18, 10, 14, 19])

In [41]:
np.random.randint(10, 20, size = (3, 5))

array([[16, 15, 17, 18, 18],
       [19, 12, 18, 16, 16],
       [19, 11, 16, 18, 18]])

In [42]:
# 정수 데이터 카운팅
# 난수가 정수값이면 unique명령이나 bincount 명령으로 데이터 값 분석 가능

# unique()함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 
# 리스트를 출력한다.

# returns_counts 인수를 True로 설정하면 각 값의 데이터 개수도 출력

np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [43]:
a = np.array(['a', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts = True)

In [44]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [45]:
count

array([2, 1, 1], dtype=int64)

In [46]:
# unique()는 데이터에 존재하는 값에 대해서만 개수를 세므로
# 데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는
# 경우에는 정보를 주지 않는다.

# 예를 들어 주사위를 10번 던졌는데 6이 한 번도 나오지 않으면 
# 이 값을 0으로 세어주지 않는다.

# 따라서 데이터가 주사위를 던졌을 때 나오는 수처럼 특정 범위안의 
# 수인 경우에는 bincount 함수에 minlength 인수를 설정하여 쓰는 것이
# 편리하다. bincount 함수는 0부터 minlength -1까지의 숫자에 대해 
# 각각 카운트를 한다. 데이터가 없을 경우에는 카운트 값이 0이 된다.

np.bincount([1, 1, 2, 2, 2, 3], minlength = 6)

array([0, 2, 3, 1, 0, 0], dtype=int64)

In [47]:
# 0 ~ 5에 대하여 카운트 (minlength가 6이므로)