In [1]:
import numpy as np

In [2]:
np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [3]:
np.array([[_ for _ in range(10, 41, 10)], 
          [_ for _ in range(50, 81, 10)]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [4]:
m = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])

In [5]:
m[1,2]

7

In [6]:
m[2,-1]

14

In [7]:
m[1, 1:3]

array([6, 7])

In [8]:
m[1:, 2]

array([ 7, 12])

In [9]:
m[:2, 3:]

array([[3, 4],
       [8, 9]])

In [10]:
zeros = np.zeros([3, 3])
ones = np.ones([3, 2])
numbers = np.reshape(np.arange(10, 160, 10), (3, -1))
res = np.tile(np.vstack([np.hstack([zeros, ones]), numbers]), (2,1))
res

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [11]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

In [12]:
practice.max()

9.0

In [13]:
practice.sum(axis = 0)

array([20.1, 27. , 23.6, 26. , 28.2, 26.5])

In [14]:
practice.max(axis = 0)

array([8.2, 8.8, 8. , 9. , 7.7, 8.9])

In [15]:
practice.mean(axis = 1)

array([5.33333333, 5.11666667, 5.71666667, 4.11666667, 4.95      ])

In [16]:
practice.min(axis = 1)

array([1.1, 2.7, 0.7, 0.2, 2.7])

In [17]:
scores = np.array([[1, 2, 3, 4],
                   [46, 99 ,100, 71],
                   [81, 59, 90, 100]])

In [18]:
rank = np.argsort(scores[1,:]) 
# argsort를 활용하여 두 번째 행을 크기순 정렬(인덱스로 위치 저장)

In [19]:
print(scores[:, rank])
# 2행의 인덱스를 기준으로 1행과 3행의 인덱스를 같이 정렬

[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]


In [20]:
np.random.seed(0)
res = np.random.randint(0, 2, 100)
res.sum() / len(res)

0.56

In [21]:
np.random.seed(0)
res = np.random.randint(2, size = 100)
res.mean()

0.56

In [22]:
np.random.seed(0)
k = [np.random.randint(0, 2) for _ in range(100) ]
np.mean(k)

0.56

In [23]:
np.random.seed(0)
res2 = np.random.randint(1, 7, 100)
res2.mean()

3.42